import "@/styles/header.css";
import "@/styles/footer.css";
import "@/styles/reset.css";
import "@/styles/main.css";
import "@/styles/userForm.css";
import "@/styles/patient.css";
import "@/styles/pagination.css";


import AppShell from "@/app/AppShell.js";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="layout-container">
        <AppShell >{children}</AppShell>
      </body>
    </html>
  );
}
