import "@/styles/header.css";
import "@/styles/footer.css";
import "@/styles/reset.css";
import "@/styles/main.css";
import "@/styles/userForm.css";


import AppShell from "@/app/AppShell.js";
// import Header from "@/components/commons/Header.jsx";
// import Footer from "@/components/commons/Footer.jsx";
// import {AuthHydrator} from "@/app/provider/AuthHydrator.jsx";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="layout-container">
        <AppShell >{children}</AppShell>
        {/*<AuthHydrator />*/}
        {/*<Header />*/}
        {/*{children}*/}
        {/*<Footer />*/}
      </body>
    </html>
  );
}
