// import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/header.css";
import "@/styles/footer.css";
import "@/styles/reset.css";
import "@/styles/main.css";
import "@/styles/userForm.css";

import Header from "@/components/commons/Header.jsx";
import Footer from "@/components/commons/Footer";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });
//
// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
